### ISSUE TITLE
Installer continuously installs helm charts

### ISSUE THREAD

**Issue by braghettos** [krateoplatformops/installer#27]
**Describe the bug**
The installer continuously installs helm charts even if specs are not changing, creating hundreds of revisions that produce many useless secrets.

**To Reproduce**
```
helm upgrade installer installer \
  --repo https://charts.krateo.io \
  --namespace krateo-system \
  --create-namespace \
  --install \
  --version 0.2.2 \
  --set krateoplatformops.vcluster.enabled=true
```

This behavior is because the installer installs two times the cluster helm chart (https://github.com/krateoplatformops/installer-chart/blob/1a58ce1f8a0b846f10cbb6343691f5a5d140bbbd/chart/templates/vcluster-installer.yaml#L11, https://github.com/krateoplatformops/installer-chart/blob/1a58ce1f8a0b846f10cbb6343691f5a5d140bbbd/chart/templates/vcluster-installer.yaml#L254) and continuously loops on the installation.

**Expected behavior**
Helm charts (and revisions) are updated only when specs are changing.

**Screenshots**
![image (21)](https://github.com/krateoplatformops/installer/assets/5436669/0f04c626-0441-4109-8fff-8c0a231766d4)

**Additional context**
We could provide the corresponding "helm upgrade --install" capability in the installer

**Comment by matteogastaldello** [comment]
The continuous reconciliation is not due to the behavior described above; instead, it is due to missing RBAC policies.
